In [69]:
import numpy as np
import pandas as pd
import statistics 

#Part 1: Data Cleaning
df = pd.read_csv('C:\\Lab 4 - Retail_Sales_Data.csv')
from IPython.display import display
display(df)

#This is to fill the missing numeric values in the data with mean
display(df.isnull().sum())
df.fillna(df.select_dtypes(include="number").mean(), inplace=True)  
display(df)

#This is to drop any remaining missing values which have not be been filled
df.dropna(inplace = True)
display(df)

#Ensuring all numeric columns have appropriate data types 
display(df['Quantity'].dtypes)
display(df['Price'].dtypes)
display(df['Total_Spent'].dtypes)
display(df['Discount'].dtypes)

#Converting date column to datetime type
display(df['Date'].dtypes)
df['Date'] = pd.to_datetime(df['Date'])
display(df['Date'].dtypes)

#Part 2: Data Transformation
#Creating a new column Total_Cost calculating total cost of each transaction.
df['Total_Cost']= df['Quantity']*df['Price'] - df['Discount']
display(df)

#o	Creating a new column Day_of_Week that shows the day of the week on which the transaction occurred.
df['Day_of_Week'] = df['Date'].dt.day_name()
display(df)

#Creating a new column Is_Discounted that is True if a discount was applied (Discount > 0), and False otherwise.
df['Is_Discounted'] = df['Discount']>1
display(df)

#Identifying and Handling Outliers for Total_Spent Column.
Q1 = df['Total_Spent'].quantile(0.25)
Q3 = df['Total_Spent'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers_iqr = df[(df['Total_Spent'] < lower_bound) | (df['Total_Spent'] > upper_bound)]
print(f'\nThe outliers for total_spent are:-')
display(outliers_iqr)
df = df[(df['Total_Spent'] >= lower_bound) & (df['Total_Spent'] <= upper_bound)]
display(df)

#Identifying and Handling Outliers for Quantity Column.
Q1 = df['Quantity'].quantile(0.25)
Q3 = df['Quantity'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(f'\nThe outliers for quantity are:-')
outliers_iqr = df[(df['Quantity'] < lower_bound) | (df['Quantity'] > upper_bound)]
display(outliers_iqr)
df = df[(df['Quantity'] >= lower_bound) & (df['Quantity'] <= upper_bound)]
display(df)

#Part 3: Data Analysis
#Desciptive Statistics
# mean_quantity = df['Quantity'].mean().round(2)
# median_quantity = df['Quantity'].median().round(2)
# std_quantity = df['Quantity'].std().round(2)
# var_quantity =df['Quantity'].var().round(2)
# range_quantity= df['Quantity'].max() - df['Quantity'].min()
# print(f"The mean quantity is: {mean_quantity}")
# print(f"The median quantity is: {median_quantity}")
# print(f"The standard deviation of quantity is: {std_quantity}")
# print(f"The variance of quantity is: {var_quantity}")
# print(f"The range of quantity is: {range_quantity}")


# mean_Price = df['Price'].mean().round(2)
# median_Price = df['Price'].median().round(2)
# std_Price = df['Price'].std().round(2)
# var_Price =df['Price'].var().round(2)
# range_Price= (df['Price'].max() - df['Price'].min()).round(2)
# print(f"\nThe mean Price is: {mean_Price}")
# print(f"The median Price is: {median_Price}")
# print(f"The standard deviation of Price is: {std_Price}")
# print(f"The variance of Price is: {var_Price}")
# print(f"The range of Price is: {range_Price}")


# mean_Total_Spent = df['Total_Spent'].mean().round(2)
# median_Total_Spent = df['Total_Spent'].median().round(2)
# std_Total_Spent = df['Total_Spent'].std().round(2)
# var_Total_Spent =df['Total_Spent'].var().round(2)
# range_Total_Spent= (df['Total_Spent'].max() - df['Total_Spent'].min()).round(2)
# print(f"\nThe mean Total_Spent is: {mean_Total_Spent}")
# print(f"The median Total_Spent is: {median_Total_Spent}")
# print(f"The standard deviation of Total_Spent is: {std_Total_Spent}")
# print(f"The variance of Total_Spent is: {var_Total_Spent}")
# print(f"The range of Total_Spent is: {range_Total_Spent}")


# mean_Discount = df['Discount'].mean().round(2)
# median_Discount = df['Discount'].median().round(2)
# std_Discount = df['Discount'].std().round(2)
# var_Discount =df['Discount'].var().round(2)
# range_Discount= (df['Discount'].max() - df['Discount'].min()).round(2)
# print(f"\nThe mean Discount is: {mean_Discount}")
# print(f"The median Discount is: {median_Discount}")
# print(f"The standard deviation of Discount is: {std_Discount}")
# print(f"The variance of Discount is: {var_Discount}")
# print(f"The range of Discount is: {range_Discount}")

# mean_Total_Cost = df['Total_Cost'].mean().round(2)
# median_Total_Cost = df['Total_Cost'].median().round(2)
# std_Total_Cost = df['Total_Cost'].std().round(2)
# var_Total_Cost =df['Total_Cost'].var().round(2)
# range_Total_Cost= df['Total_Cost'].max() - df['Total_Cost'].min()
# print(f"\nThe mean Total_Cost is: {mean_Total_Cost}")
# print(f"The median Total_Cost is: {median_Total_Cost}")
# print(f"The standard deviation of Total_Cost is: {std_Total_Cost}")
# print(f"The variance of Total_Cost is: {var_Total_Cost}")
# print(f"The range of Total_Cost is: {range_Total_Cost}")

display(df.drop(columns=['Date','Transaction_ID','Customer_ID']).describe())


#Transaction Analysis
top_spender = df.groupby('Customer_ID')['Total_Spent'].sum()
print(f'Customer_ID {top_spender.idxmax()} is the customer with the highest total spending.')

popular_product = df.groupby('Product')['Quantity'].sum()
print(f'{popular_product.idxmax()} is the most popular product.')

#Timw-Based Analysis
highest_total_sales = df.groupby('Day_of_Week')['Total_Cost'].sum()
print(f'Highest total sales occurs on {highest_total_sales.idxmax()}.')

lowest_total_sales = df.groupby('Day_of_Week')['Total_Cost'].sum()
print(f'Lowest total sales occurs on {lowest_total_sales.idxmin()}.')

#Correlation Analysis
# numerical_columns = df.select_dtypes(include='number').drop(columns=['Transaction_ID']).corr()
# df[numerical_columns]

numerical_columns = df.drop(columns=['Transaction_ID','Customer_ID']).select_dtypes(include=[np.number]).columns
df[numerical_columns].corr()

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method
0,6119,2023-08-02 06:00:00,2950,Headphones,1,NaN,738.09,85.18,PayPal
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.05,4925.71,30.44,Credit Card
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.58,643.71,16.87,Cash
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.84,2957.98,68.54,PayPal
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.05,2154.41,27.69,Debit Card
...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.11,379.82,79.51,Debit Card
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.29,1814.37,48.21,PayPal
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.30,64.80,87.50,Credit Card
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.13,437.19,91.94,Cash
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.55,5434.86,51.34,Credit Card

Transaction_ID      0
Date                0
Customer_ID         0
Product             0
Quantity            0
Price             520
Total_Spent       316
Discount            0
Payment_Method    207
dtype: int64

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card
...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card
...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card

dtype('int64')

dtype('float64')

dtype('float64')

dtype('float64')

dtype('O')

dtype('<M8[ns]')

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method,Total_Cost
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal,929.194055
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card,4925.710000
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash,643.710000
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal,2957.980000
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card,2154.410000
...,...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card,379.820000
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal,1814.370000
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card,64.800000
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash,437.190000
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card,5434.860000

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method,Total_Cost,Day_of_Week
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal,929.194055,Wednesday
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card,4925.710000,Monday
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash,643.710000,Thursday
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal,2957.980000,Tuesday
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card,2154.410000,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card,379.820000,Sunday
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal,1814.370000,Saturday
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card,64.800000,Sunday
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash,437.190000,Sunday
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card,5434.860000,Monday

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method,Total_Cost,Day_of_Week,Is_Discounted
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal,929.194055,Wednesday,True
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card,4925.710000,Monday,True
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash,643.710000,Thursday,True
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal,2957.980000,Tuesday,True
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card,2154.410000,Tuesday,True
...,...,...,...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card,379.820000,Sunday,True
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal,1814.370000,Saturday,True
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card,64.800000,Sunday,True
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash,437.190000,Sunday,True
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card,5434.860000,Monday,True

The outliers for total_spent are:-

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method,Total_Cost,Day_of_Week,Is_Discounted
97,2651,2023-03-10 18:00:00,2825,Monitor,4,1952.490000,7723.42,86.54,Credit Card,7723.42000,Friday,True
167,3393,2023-04-10 16:00:00,2657,Monitor,4,1901.560000,7601.32,4.92,Debit Card,7601.32000,Monday,True
190,2685,2023-03-12 04:00:00,2955,Mouse,4,1950.640000,7775.06,27.50,Credit Card,7775.06000,Sunday,True
401,5050,2023-06-18 17:00:00,2998,Tablet,4,1934.950000,7709.97,29.83,PayPal,7709.97000,Sunday,True
412,8202,2023-10-28 01:00:00,2094,Keyboard,4,1014.374055,7611.01,41.03,Debit Card,4016.46622,Saturday,True
...,...,...,...,...,...,...,...,...,...,...,...,...
9934,7314,2023-09-21 01:00:00,2942,Headphones,4,1929.050000,7705.86,10.34,Credit Card,7705.86000,Thursday,True
10147,1538,2023-01-23 09:00:00,2351,Monitor,4,1914.090000,7634.91,21.45,Credit Card,7634.91000,Monday,True
10215,5736,2023-07-17 07:00:00,2680,Monitor,4,1939.730000,7731.41,27.51,PayPal,7731.41000,Monday,True
10309,6027,2023-07-29 10:00:00,2337,Mouse,4,1952.280000,7742.11,67.01,PayPal,7742.11000,Saturday,True
10312,1855,2023-02-05 14:00:00,2984,Headphones,4,1925.110000,7632.48,67.96,Credit Card,7632.48000,Sunday,True

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method,Total_Cost,Day_of_Week,Is_Discounted
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal,929.194055,Wednesday,True
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card,4925.710000,Monday,True
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash,643.710000,Thursday,True
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal,2957.980000,Tuesday,True
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card,2154.410000,Tuesday,True
...,...,...,...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card,379.820000,Sunday,True
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal,1814.370000,Saturday,True
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card,64.800000,Sunday,True
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash,437.190000,Sunday,True
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card,5434.860000,Monday,True

The outliers for quantity are:-

Empty DataFrame
Columns: [Transaction_ID, Date, Customer_ID, Product, Quantity, Price, Total_Spent, Discount, Payment_Method, Total_Cost, Day_of_Week, Is_Discounted]
Index: []

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method,Total_Cost,Day_of_Week,Is_Discounted
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal,929.194055,Wednesday,True
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card,4925.710000,Monday,True
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash,643.710000,Thursday,True
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal,2957.980000,Tuesday,True
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card,2154.410000,Tuesday,True
...,...,...,...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card,379.820000,Sunday,True
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal,1814.370000,Saturday,True
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card,64.800000,Sunday,True
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash,437.190000,Sunday,True
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card,5434.860000,Monday,True

           Quantity         Price   Total_Spent      Discount    Total_Cost
count  10174.000000  10174.000000  10174.000000  10174.000000  10174.000000
mean       2.489286   1005.464635   2435.977949     50.179933   2436.831554
std        1.113191    549.704245   1824.511959     28.632351   1827.789164
min        1.000000     20.530000    -66.460000      0.010000    -66.460000
25%        2.000000    547.617500    975.212500     25.307500    964.022500
50%        2.000000   1014.374055   1960.150000     50.385000   1936.234055
75%        3.000000   1474.222500   3570.182500     74.940000   3618.502500
max        4.000000   1999.390000   7579.270000     99.990000   7970.310000

Customer_ID 2286 is the customer with the highest total spending.
Laptop is the most popular product.
Highest total sales occurs on Monday.
Lowest total sales occurs on Saturday.

             Quantity     Price  Total_Spent  Discount  Total_Cost
Quantity     1.000000 -0.025950     0.562713  0.007508    0.583281
Price       -0.025950  1.000000     0.700278 -0.006285    0.725945
Total_Spent  0.562713  0.700278     1.000000 -0.016357    0.964679
Discount     0.007508 -0.006285    -0.016357  1.000000   -0.012238
Total_Cost   0.583281  0.725945     0.964679 -0.012238    1.000000