In [10]:
import numpy as np
import pandas as pd
from IPython.display import display

# Part 1: Data Cleaning
# Load dataset
df = pd.read_csv('/Users/prabhusana/Downloads/Lab 4 - Retail_Sales_Data.csv')
display(df)

# Check for missing values
display(df.isnull().sum())

# Fill missing numeric values with mean
df.fillna(df.select_dtypes(include="number").mean(), inplace=True)
display(df)

# Drop remaining missing values (non-numeric or not filled)
df.dropna(inplace=True)
display(df)

# Convert Date column to datetime
display(df['Date'].dtypes)
df['Date'].dtype
df['Date'] = pd.to_datetime(df['Date'])

# Check data types of numeric columns
print('The data types of the dataset is:')
df.info()

# Part 2: Data Transformation
# Create Total_Cost column (Quantity * Price - Discount)
df['Total_Cost'] = df['Quantity'] * df['Price'] - df['Discount']
display(df)

# Create Day_of_Week column from Date
df['Day_of_Week'] = df['Date'].dt.day_name()
display(df)

# Create Is_Discounted column (True if Discount > 0)
df['Is_Discounted'] = df['Discount'] > 0
display(df)

# Handle outliers for Total_Spent using IQR
Q1 = df['Total_Spent'].quantile(0.25)
Q3 = df['Total_Spent'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers_iqr = df[(df['Total_Spent'] < lower_bound) | (df['Total_Spent'] > upper_bound)]
print('\nThe outliers for Total_Spent are:')
display(outliers_iqr)
df = df[(df['Total_Spent'] >= lower_bound) & (df['Total_Spent'] <= upper_bound)]
display(df)


Q1 = df['Total_Spent'].quantile(0.25)
Q3 = df['Total_Spent'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers_iqr = df[(df['Total_Spent'] < lower_bound) | (df['Total_Spent'] > upper_bound)]
print('\nThe outliers for Total_Spent are:')
display(outliers_iqr)
df = df[(df['Total_Spent'] >= lower_bound) & (df['Total_Spent'] <= upper_bound)]
display(df)

# Handle outliers for Quantity using IQR

Q1 = df['Quantity'].quantile(0.25)
Q3 = df['Quantity'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print('\nThe outliers for Quantity are:')
outliers_iqr = df[(df['Quantity'] < lower_bound) | (df['Quantity'] > upper_bound)]
display(outliers_iqr)
df = df[(df['Quantity'] >= lower_bound) & (df['Quantity'] <= upper_bound)]
display(df)

# Part 3: Data Analysis
# Descriptive statistics (excluding non-relevant columns)
display(df.drop(columns=['Date', 'Transaction_ID', 'Customer_ID', 'Product', 'Payment_Method', 'Day_of_Week', 'Is_Discounted']).describe())

# Transaction Analysis
top_spender = df.groupby('Customer_ID')['Total_Spent'].sum()
print(f'Customer_ID {top_spender.idxmax()} is the customer with the highest total spending.')

popular_product = df.groupby('Product')['Quantity'].sum()
print(f'{popular_product.idxmax()} is the most popular product.')

# Time-Based Analysis
highest_total_sales = df.groupby('Day_of_Week')['Total_Cost'].sum()
print(f'Highest total sales occurs on {highest_total_sales.idxmax()}.')

lowest_total_sales = df.groupby('Day_of_Week')['Total_Cost'].sum()
print(f'Lowest total sales occurs on {lowest_total_sales.idxmin()}.')

# Correlation Analysis
numerical_columns = df.drop(columns=['Transaction_ID', 'Customer_ID', 'Date', 'Product', 'Payment_Method', 'Day_of_Week', 'Is_Discounted']).select_dtypes(include=[np.number]).columns
correlation_matrix = df[numerical_columns].corr()
display(correlation_matrix)

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method
0,6119,2023-08-02 06:00:00,2950,Headphones,1,NaN,738.09,85.18,PayPal
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.05,4925.71,30.44,Credit Card
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.58,643.71,16.87,Cash
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.84,2957.98,68.54,PayPal
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.05,2154.41,27.69,Debit Card
...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.11,379.82,79.51,Debit Card
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.29,1814.37,48.21,PayPal
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.30,64.80,87.50,Credit Card
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.13,437.19,91.94,Cash
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.55,5434.86,51.34,Credit Card

Transaction_ID      0
Date                0
Customer_ID         0
Product             0
Quantity            0
Price             520
Total_Spent       316
Discount            0
Payment_Method    207
dtype: int64

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card
...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card
...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card

dtype('O')

The data types of the dataset is:
<class 'pandas.core.frame.DataFrame'>
Index: 10293 entries, 0 to 10499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  10293 non-null  int64
 1   Date            10293 non-null  datetime64[ns]
 2   Customer_ID     10293 non-null  int64
 3   Product         10293 non-null  object
 4   Quantity        10293 non-null  int64
 5   Price           10293 non-null  float64
 6   Total_Spent     10293 non-null  float64
 7   Discount        10293 non-null  float64
 8   Payment_Method  10293 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(3), object(2)
memory usage: 804.1+ KB

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method,Total_Cost
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal,929.194055
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card,4925.710000
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash,643.710000
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal,2957.980000
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card,2154.410000
...,...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card,379.820000
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal,1814.370000
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card,64.800000
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash,437.190000
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card,5434.860000

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method,Total_Cost,Day_of_Week
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal,929.194055,Wednesday
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card,4925.710000,Monday
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash,643.710000,Thursday
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal,2957.980000,Tuesday
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card,2154.410000,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card,379.820000,Sunday
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal,1814.370000,Saturday
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card,64.800000,Sunday
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash,437.190000,Sunday
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card,5434.860000,Monday

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method,Total_Cost,Day_of_Week,Is_Discounted
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal,929.194055,Wednesday,True
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card,4925.710000,Monday,True
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash,643.710000,Thursday,True
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal,2957.980000,Tuesday,True
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card,2154.410000,Tuesday,True
...,...,...,...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card,379.820000,Sunday,True
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal,1814.370000,Saturday,True
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card,64.800000,Sunday,True
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash,437.190000,Sunday,True
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card,5434.860000,Monday,True

The outliers for Total_Spent are:

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method,Total_Cost,Day_of_Week,Is_Discounted
97,2651,2023-03-10 18:00:00,2825,Monitor,4,1952.490000,7723.42,86.54,Credit Card,7723.42000,Friday,True
167,3393,2023-04-10 16:00:00,2657,Monitor,4,1901.560000,7601.32,4.92,Debit Card,7601.32000,Monday,True
190,2685,2023-03-12 04:00:00,2955,Mouse,4,1950.640000,7775.06,27.50,Credit Card,7775.06000,Sunday,True
401,5050,2023-06-18 17:00:00,2998,Tablet,4,1934.950000,7709.97,29.83,PayPal,7709.97000,Sunday,True
412,8202,2023-10-28 01:00:00,2094,Keyboard,4,1014.374055,7611.01,41.03,Debit Card,4016.46622,Saturday,True
...,...,...,...,...,...,...,...,...,...,...,...,...
9934,7314,2023-09-21 01:00:00,2942,Headphones,4,1929.050000,7705.86,10.34,Credit Card,7705.86000,Thursday,True
10147,1538,2023-01-23 09:00:00,2351,Monitor,4,1914.090000,7634.91,21.45,Credit Card,7634.91000,Monday,True
10215,5736,2023-07-17 07:00:00,2680,Monitor,4,1939.730000,7731.41,27.51,PayPal,7731.41000,Monday,True
10309,6027,2023-07-29 10:00:00,2337,Mouse,4,1952.280000,7742.11,67.01,PayPal,7742.11000,Saturday,True
10312,1855,2023-02-05 14:00:00,2984,Headphones,4,1925.110000,7632.48,67.96,Credit Card,7632.48000,Sunday,True

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method,Total_Cost,Day_of_Week,Is_Discounted
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal,929.194055,Wednesday,True
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card,4925.710000,Monday,True
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash,643.710000,Thursday,True
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal,2957.980000,Tuesday,True
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card,2154.410000,Tuesday,True
...,...,...,...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card,379.820000,Sunday,True
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal,1814.370000,Saturday,True
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card,64.800000,Sunday,True
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash,437.190000,Sunday,True
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card,5434.860000,Monday,True

The outliers for Total_Spent are:

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method,Total_Cost,Day_of_Week,Is_Discounted
380,2083,2023-02-15 02:00:00,2511,Laptop,4,1014.374055,7576.33,8.71,Cash,4048.78622,Wednesday,True
654,5788,2023-07-19 11:00:00,2772,Tablet,4,1906.040000,7539.12,85.04,Credit Card,7539.12000,Wednesday,True
697,9238,2023-12-10 05:00:00,2060,Laptop,4,1880.690000,7487.26,35.50,Cash,7487.26000,Sunday,True
704,1107,2023-01-05 10:00:00,2742,Monitor,4,1889.920000,7525.35,34.33,Cash,7525.35000,Thursday,True
732,1030,2023-01-02 05:00:00,2787,Monitor,4,1898.170000,7534.32,58.36,Cash,7534.32000,Monday,True
1245,2607,2023-03-08 22:00:00,2852,Keyboard,4,1904.870000,7556.92,62.56,Cash,7556.92000,Wednesday,True
1412,6406,2023-08-14 05:00:00,2327,Headphones,4,1891.370000,7480.87,84.61,Credit Card,7480.87000,Monday,True
1761,4334,2023-05-19 21:00:00,2433,Keyboard,4,1894.760000,7520.20,58.84,Credit Card,7520.20000,Friday,True
1816,8432,2023-11-06 15:00:00,2600,Laptop,4,1883.890000,7511.40,24.16,Cash,7511.40000,Monday,True
2317,2347,2023-02-26 02:00:00,2958,Headphones,4,1891.200000,7511.68,53.12,Credit Card,7511.68000,Sunday,True
2610,6835,2023-09-01 02:00:00,2585,Monitor,4,1894.920000,7519.71,59.97,Debit Card,7519.71000,Friday,True
2894,5032,2023-06-17 23:00:00,2136,Mouse,4,1878.810000,7486.24,29.00,Credit Card,7486.24000,Saturday,True
3368,9987,2024-01-10 10:00:00,2299,Headphones,4,1885.780000,7521.37,21.75,Credit Card,7521.37000,Wednesday,True
3973,5265,2023-06-27 16:00:00,2187,Monitor,4,1885.500000,7496.78,45.22,PayPal,7496.78000,Tuesday,True
4085,8714,2023-11-18 09:00:00,2385,Headphones,4,1879.750000,7495.38,23.62,Credit Card,7495.38000,Saturday,True
4092,9471,2023-12-19 22:00:00,2324,Tablet,4,1900.020000,7579.27,20.81,Debit Card,7579.27000,Tuesday,True
4134,1535,2023-01-23 06:00:00,2503,Laptop,4,1891.800000,7483.25,83.95,PayPal,7483.25000,Monday,True
4335,8863,2023-11-24 14:00:00,2681,Tablet,4,1895.470000,7531.16,50.72,Debit Card,7531.16000,Friday,True
4579,7891,2023-10-15 02:00:00,2924,Tablet,4,1878.010000,7466.11,45.93,Credit Card,7466.11000,Sunday,True
4982,10862,2024-02-15 21:00:00,2796,Laptop,4,1880.960000,7493.62,30.22,Cash,7493.62000,Thursday,True
5245,6903,2023-09-03 22:00:00,2356,Tablet,4,1884.150000,7503.68,32.92,Credit Card,7503.68000,Sunday,True
5339,1030,2023-01-02 05:00:00,2787,Monitor,4,1898.170000,7534.32,58.36,Cash,7534.32000,Monday,True
6145,6405,2023-08-14 04:00:00,2346,Tablet,4,1878.660000,7493.47,21.17,Credit Card,7493.47000,Monday,True
6146,8992,2023-11-29 23:00:00,2579,Mouse,4,1877.450000,7465.30,44.50,Cash,7465.30000,Wednesday,True
6279,3347,2023-04-08 18:00:00,2968,Laptop,4,1884.030000,7477.77,58.35,Cash,7477.77000,Saturday,True
6291,3805,2023-04-27 20:00:00,2871,Tablet,4,1907.250000,7565.69,63.31,Debit Card,7565.69000,Thursday,True
7330,5700,2023-07-15 19:00:00,2333,Keyboard,4,1897.160000,7527.47,61.17,Credit Card,7527.47000,Saturday,True
7484,4416,2023-05-23 07:00:00,2434,Headphones,4,1888.510000,7487.34,66.70,PayPal,7487.34000,Tuesday,True
8239,1163,2023-01-07 18:00:00,2575,Keyboard,4,1889.110000,7466.54,89.90,Cash,7466.54000,Saturday,True
8743,2607,2023-03-08 22:00:00,2852,Keyboard,4,1904.870000,7556.92,62.56,Cash,7556.92000,Wednesday,True
8930,1107,2023-01-05 10:00:00,2742,Monitor,4,1889.920000,7525.35,34.33,Cash,7525.35000,Thursday,True
9167,8833,2023-11-23 08:00:00,2558,Tablet,4,1880.670000,7464.94,57.74,Debit Card,7464.94000,Thursday,True
9287,2763,2023-03-15 10:00:00,2042,Keyboard,4,1915.440000,7562.88,98.88,Cash,7562.88000,Wednesday,True
9340,6878,2023-09-02 21:00:00,2150,Laptop,4,1913.830000,7557.50,97.82,Credit Card,7557.50000,Saturday,True
9365,4595,2023-05-30 18:00:00,2461,Laptop,4,1901.490000,7525.66,80.30,Debit Card,7525.66000,Tuesday,True
10290,8126,2023-10-24 21:00:00,2814,Laptop,4,1900.970000,7550.16,53.72,Debit Card,7550.16000,Tuesday,True
10422,7864,2023-10-13 23:00:00,2233,Headphones,4,1900.000000,7506.60,93.40,Credit Card,7506.60000,Friday,True

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method,Total_Cost,Day_of_Week,Is_Discounted
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal,929.194055,Wednesday,True
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card,4925.710000,Monday,True
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash,643.710000,Thursday,True
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal,2957.980000,Tuesday,True
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card,2154.410000,Tuesday,True
...,...,...,...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card,379.820000,Sunday,True
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal,1814.370000,Saturday,True
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card,64.800000,Sunday,True
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash,437.190000,Sunday,True
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card,5434.860000,Monday,True

The outliers for Quantity are:

Empty DataFrame
Columns: [Transaction_ID, Date, Customer_ID, Product, Quantity, Price, Total_Spent, Discount, Payment_Method, Total_Cost, Day_of_Week, Is_Discounted]
Index: []

,Transaction_ID,Date,Customer_ID,Product,Quantity,Price,Total_Spent,Discount,Payment_Method,Total_Cost,Day_of_Week,Is_Discounted
0,6119,2023-08-02 06:00:00,2950,Headphones,1,1014.374055,738.09,85.18,PayPal,929.194055,Wednesday,True
1,9932,2024-01-08 03:00:00,2272,Headphones,3,1652.050000,4925.71,30.44,Credit Card,4925.710000,Monday,True
2,9516,2023-12-21 19:00:00,2007,Tablet,1,660.580000,643.71,16.87,Cash,643.710000,Thursday,True
3,8283,2023-10-31 10:00:00,2787,Keyboard,3,1008.840000,2957.98,68.54,PayPal,2957.980000,Tuesday,True
4,8624,2023-11-14 15:00:00,2281,Mouse,2,1091.050000,2154.41,27.69,Debit Card,2154.410000,Tuesday,True
...,...,...,...,...,...,...,...,...,...,...,...,...
10495,6735,2023-08-27 22:00:00,2911,Headphones,3,153.110000,379.82,79.51,Debit Card,379.820000,Sunday,True
10496,6192,2023-08-05 07:00:00,2488,Headphones,2,931.290000,1814.37,48.21,PayPal,1814.370000,Saturday,True
10497,6391,2023-08-13 14:00:00,2141,Tablet,1,152.300000,64.80,87.50,Credit Card,64.800000,Sunday,True
10498,1861,2023-02-05 20:00:00,2471,Monitor,1,529.130000,437.19,91.94,Cash,437.190000,Sunday,True
10499,8271,2023-10-30 22:00:00,2990,Laptop,4,1371.550000,5434.86,51.34,Credit Card,5434.860000,Monday,True

           Quantity         Price   Total_Spent      Discount    Total_Cost
count  10137.000000  10137.000000  10137.000000  10137.000000  10137.000000
mean       2.483772   1002.314217   2417.436295     50.166626   2418.641003
std        1.111466    548.155108   1801.790337     28.647717   1805.783944
min        1.000000     20.530000    -66.460000      0.010000    -66.460000
25%        1.000000    546.410000    973.330000     25.290000    961.670000
50%        2.000000   1014.374055   1944.980000     50.370000   1930.500000
75%        3.000000   1467.970000   3552.150000     74.970000   3595.630000
max        4.000000   1999.390000   7459.170000     99.990000   7970.310000

Customer_ID 2286 is the customer with the highest total spending.
Laptop is the most popular product.
Highest total sales occurs on Monday.
Lowest total sales occurs on Saturday.

             Quantity     Price  Total_Spent  Discount  Total_Cost
Quantity     1.000000 -0.034000     0.558737  0.006909    0.579720
Price       -0.034000  1.000000     0.697449 -0.007340    0.723340
Total_Spent  0.558737  0.697449     1.000000 -0.017931    0.963855
Discount     0.006909 -0.007340    -0.017931  1.000000   -0.014017
Total_Cost   0.579720  0.723340     0.963855 -0.014017    1.000000